server:
  port: 8080

spring:
  profiles:
    active: ${APP_ENV:local}
  application:
    name: malenia
  web:
    resources:
      add-mappings: false    # Handle NoHandlerFoundException 需要
  mvc:
    throw-exception-if-no-handler-found: true    # Handle NoHandlerFoundException 需要

  jackson:
    serialization:
      fail-on-empty-beans: false    # 对 `无任何字段的对象` 进行序列化时, 不报错

# actuator
info:
  app:
    name: ${spring.application.name}
    version: 1.0
management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'

logging:
  config: classpath:logback/configuration.xml

feign:
  circuitbreaker:
    enabled: true
